<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\net8.0-windows\GongSolutions.Wpf.DragDrop.xml</DocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\net8.0-windows\GongSolutions.Wpf.DragDrop.xml</DocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="GongSolutions.Wpf.DragDrop.nuspec" />
    <None Remove="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="GongSolutions.Wpf.DragDrop.UnitTests" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\EffectCopy.png" />
    <Resource Include="Icons\EffectLink.png" />
    <Resource Include="Icons\EffectMove.png" />
    <Resource Include="Icons\EffectNone.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>